/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppWarRoomRouteImport } from './routes/_app.war-room'
import { Route as AppSalesTeamRouteImport } from './routes/_app.sales-team'
import { Route as AppIntakeRouteImport } from './routes/_app.intake'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppCommitmentsRouteImport } from './routes/_app.commitments'
import { Route as AppCeoPulseRouteImport } from './routes/_app.ceo-pulse'
import { Route as AppAskAiRouteImport } from './routes/_app.ask-ai'
import { Route as ApiPublicSeedDemoRouteImport } from './routes/api/public/seed-demo'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWarRoomRoute = AppWarRoomRouteImport.update({
  id: '/war-room',
  path: '/war-room',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesTeamRoute = AppSalesTeamRouteImport.update({
  id: '/sales-team',
  path: '/sales-team',
  getParentRoute: () => AppRoute,
} as any)
const AppIntakeRoute = AppIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCommitmentsRoute = AppCommitmentsRouteImport.update({
  id: '/commitments',
  path: '/commitments',
  getParentRoute: () => AppRoute,
} as any)
const AppCeoPulseRoute = AppCeoPulseRouteImport.update({
  id: '/ceo-pulse',
  path: '/ceo-pulse',
  getParentRoute: () => AppRoute,
} as any)
const AppAskAiRoute = AppAskAiRouteImport.update({
  id: '/ask-ai',
  path: '/ask-ai',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicSeedDemoRoute = ApiPublicSeedDemoRouteImport.update({
  id: '/api/public/seed-demo',
  path: '/api/public/seed-demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/ask-ai': typeof AppAskAiRoute
  '/ceo-pulse': typeof AppCeoPulseRoute
  '/commitments': typeof AppCommitmentsRoute
  '/customers': typeof AppCustomersRoute
  '/intake': typeof AppIntakeRoute
  '/sales-team': typeof AppSalesTeamRoute
  '/war-room': typeof AppWarRoomRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/ask-ai': typeof AppAskAiRoute
  '/ceo-pulse': typeof AppCeoPulseRoute
  '/commitments': typeof AppCommitmentsRoute
  '/customers': typeof AppCustomersRoute
  '/intake': typeof AppIntakeRoute
  '/sales-team': typeof AppSalesTeamRoute
  '/war-room': typeof AppWarRoomRoute
  '/': typeof AppIndexRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/ask-ai': typeof AppAskAiRoute
  '/_app/ceo-pulse': typeof AppCeoPulseRoute
  '/_app/commitments': typeof AppCommitmentsRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/intake': typeof AppIntakeRoute
  '/_app/sales-team': typeof AppSalesTeamRoute
  '/_app/war-room': typeof AppWarRoomRoute
  '/_app/': typeof AppIndexRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ask-ai'
    | '/ceo-pulse'
    | '/commitments'
    | '/customers'
    | '/intake'
    | '/sales-team'
    | '/war-room'
    | '/api/public/seed-demo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/ask-ai'
    | '/ceo-pulse'
    | '/commitments'
    | '/customers'
    | '/intake'
    | '/sales-team'
    | '/war-room'
    | '/'
    | '/api/public/seed-demo'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/ask-ai'
    | '/_app/ceo-pulse'
    | '/_app/commitments'
    | '/_app/customers'
    | '/_app/intake'
    | '/_app/sales-team'
    | '/_app/war-room'
    | '/_app/'
    | '/api/public/seed-demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicSeedDemoRoute: typeof ApiPublicSeedDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/war-room': {
      id: '/_app/war-room'
      path: '/war-room'
      fullPath: '/war-room'
      preLoaderRoute: typeof AppWarRoomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales-team': {
      id: '/_app/sales-team'
      path: '/sales-team'
      fullPath: '/sales-team'
      preLoaderRoute: typeof AppSalesTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intake': {
      id: '/_app/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AppIntakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/commitments': {
      id: '/_app/commitments'
      path: '/commitments'
      fullPath: '/commitments'
      preLoaderRoute: typeof AppCommitmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ceo-pulse': {
      id: '/_app/ceo-pulse'
      path: '/ceo-pulse'
      fullPath: '/ceo-pulse'
      preLoaderRoute: typeof AppCeoPulseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ask-ai': {
      id: '/_app/ask-ai'
      path: '/ask-ai'
      fullPath: '/ask-ai'
      preLoaderRoute: typeof AppAskAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/seed-demo': {
      id: '/api/public/seed-demo'
      path: '/api/public/seed-demo'
      fullPath: '/api/public/seed-demo'
      preLoaderRoute: typeof ApiPublicSeedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAskAiRoute: typeof AppAskAiRoute
  AppCeoPulseRoute: typeof AppCeoPulseRoute
  AppCommitmentsRoute: typeof AppCommitmentsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppIntakeRoute: typeof AppIntakeRoute
  AppSalesTeamRoute: typeof AppSalesTeamRoute
  AppWarRoomRoute: typeof AppWarRoomRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAskAiRoute: AppAskAiRoute,
  AppCeoPulseRoute: AppCeoPulseRoute,
  AppCommitmentsRoute: AppCommitmentsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppIntakeRoute: AppIntakeRoute,
  AppSalesTeamRoute: AppSalesTeamRoute,
  AppWarRoomRoute: AppWarRoomRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicSeedDemoRoute: ApiPublicSeedDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
